name: Nice if example 
on:
    push:
        branches:
            - main
            - develop
            - feature/**
jobs:
    quality-checks:
        if: startsWith(github.ref_name ,'feature') && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Perform code quality
              run: |
                echo "Performing quality checks on the code on this new branch"
                exit 1

    dev-deploy:
        if: github.ref_name == 'develop' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Dev deploy
              run: echo "Deploy the code to development environment"
    prod_deploy:
        if: github.ref_name == 'main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Production deploy
              run: echo "Deploy the code to production environment"
    success-notify:
        needs: ['quality-checks', 'dev-deploy', 'prod_deploy']
        if: always() && !failure()
        runs-on: ubuntu-latest
        steps:
            - name: Notify success
              run: echo "Success email sent to the team"
    failure_notify:
        needs: ['quality-checks', 'dev-deploy', 'prod_deploy']
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Notify failure
              run: echo "Failure email sent to the team"
        
     